### ISSUE TITLE
Duplicates file issues

### ISSUE THREAD

**Issue by 5ysourcesafe** [bottotl/AVBuilder#1]
duplicate symbol _OBJC_CLASS_$_JFTAVBuilderSettings in:
    /Users/sashank/Library/Developer/Xcode/DerivedData/App-eifpsnhhcrqujxaucytfwtszuwqa/Build/Intermediates/Pods.build/Debug-iphonesimulator/JFTAVBuilder.build/Objects-normal/x86_64/JFTAVBuilder.o
    /Users/sashank/Library/Developer/Xcode/DerivedData/App-eifpsnhhcrqujxaucytfwtszuwqa/Build/Intermediates/Pods.build/Debug-iphonesimulator/JFTAVBuilder.build/Objects-normal/x86_64/JFTAVBuilderSettings.o
duplicate symbol _OBJC_METACLASS_$_JFTAVBuilderSettings in:
    /Users/sashank/Library/Developer/Xcode/DerivedData/App-eifpsnhhcrqujxaucytfwtszuwqa/Build/Intermediates/Pods.build/Debug-iphonesimulator/JFTAVBuilder.build/Objects-normal/x86_64/JFTAVBuilder.o
    /Users/sashank/Library/Developer/Xcode/DerivedData/App-eifpsnhhcrqujxaucytfwtszuwqa/Build/Intermediates/Pods.build/Debug-iphonesimulator/JFTAVBuilder.build/Objects-normal/x86_64/JFTAVBuilderSettings.o
duplicate symbol _OBJC_IVAR_$_JFTAVBuilderSettings._frameDuration in:
    /Users/sashank/Library/Developer/Xcode/DerivedData/App-eifpsnhhcrqujxaucytfwtszuwqa/Build/Intermediates/Pods.build/Debug-iphonesimulator/JFTAVBuilder.build/Objects-normal/x86_64/JFTAVBuilder.o
    /Users/sashank/Library/Developer/Xcode/DerivedData/App-eifpsnhhcrqujxaucytfwtszuwqa/Build/Intermediates/Pods.build/Debug-iphonesimulator/JFTAVBuilder.build/Objects-normal/x86_64/JFTAVBuilderSettings.o
duplicate symbol _OBJC_IVAR_$_JFTAVBuilderSettings._videoSize in:
    /Users/sashank/Library/Developer/Xcode/DerivedData/App-eifpsnhhcrqujxaucytfwtszuwqa/Build/Intermediates/Pods.build/Debug-iphonesimulator/JFTAVBuilder.build/Objects-normal/x86_64/JFTAVBuilder.o
    /Users/sashank/Library/Developer/Xcode/DerivedData/App-eifpsnhhcrqujxaucytfwtszuwqa/Build/Intermediates/Pods.build/Debug-iphonesimulator/JFTAVBuilder.build/Objects-normal/x86_64/JFTAVBuilderSettings.o
duplicate symbol _OBJC_IVAR_$_JFTAVBuilderSettings._preferredVideoSize in:
    /Users/sashank/Library/Developer/Xcode/DerivedData/App-eifpsnhhcrqujxaucytfwtszuwqa/Build/Intermediates/Pods.build/Debug-iphonesimulator/JFTAVBuilder.build/Objects-normal/x86_64/JFTAVBuilder.o
    /Users/sashank/Library/Developer/Xcode/DerivedData/App-eifpsnhhcrqujxaucytfwtszuwqa/Build/Intermediates/Pods.build/Debug-iphonesimulator/JFTAVBuilder.build/Objects-normal/x86_64/JFTAVBuilderSettings.o
ld: 5 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help me out with this duplicates

**Comment by bottotl** [comment]
Sorry ，I just break up with my girl friend today.I think I need to have a rest for about 3 days.
If you can wait,leave me your IDE environment.
:)

**Comment by bottotl** [comment]
I build this project successed.Can you zip your test project,this may help me to solve your problem.
